export { ProductId } from './ProductId.js';
export { Product } from './Product.js';
export { VariantId } from './VariantId.js';
export { Variant } from './Variant.js';
export { Sku, SkuError } from './Sku.js';
export { Alias, AliasError } from './Alias.js';
export { SupplierId } from './SupplierId.js';
export { Supplier } from './Supplier.js';
export { PurchaseId } from './PurchaseId.js';
export { Purchase } from './Purchase.js';
export { PurchaseLotId } from './PurchaseLotId.js';
export { PurchaseLot, LotConsumptionError } from './PurchaseLot.js';
export type { LotStatus, LotConsumption } from './PurchaseLot.js';
export { allocateFifo, InsufficientStockError } from './services/FifoAllocationService.js';
export type { LotSelection, FifoAllocationResult } from './services/FifoAllocationService.js';
export type { ProductRepository } from './ProductRepository.js';
export type { VariantRepository } from './VariantRepository.js';
export type { SupplierRepository } from './SupplierRepository.js';
export type { PurchaseRepository } from './PurchaseRepository.js';
export type { InventoryLotRepository } from './InventoryLotRepository.js';
export type { ProductListReadRepository, ListProductsQuery, ListProductsResult, ProductListItem, ProductVariantSummary, ListProductsMeta, ListProductsFilters } from './ProductListReadRepository.js';
